path = ["/home/spicy/.local/bin", "/home/spicy/.volta/bin", "/home/spicy/git/lua-language-server/bin/Linux"]
prompt = "starship_prompt"
skip_welcome_message = true
startup = ["zoxide init nushell --hook prompt | save ~/.zoxide.nu", "mkdir ~/.cache/starship", "starship init nu | save ~/.cache/starship/init.nu", "source ~/.cache/starship/init.nu", "alias dotgit = git --git-dir=/home/spicy/dotfiles.git --work-tree=/home/spicy", "let git = /home/spicy/git", "source ~/.zoxide.nu"]

[env]
VOLTA_HOME = "/home/spicy/.volta"
EDITOR = "nvim"
PAGER = "nvim +Man!"
MANPAGER = "nvim +Man!"

[line_editor]
edit_mode = "vi"
