skip_welcome_message = true
startup = [
 "mkdir ~/.cache/starship",
 "starship init nu | save ~/.cache/starship/init.nu",
 "source ~/.cache/starship/init.nu",
 "alias dotgit = git --git-dir=/home/spicy/dotfiles.git --work-tree=/home/spicy",
 "let git = /home/spicy/git",
 "let dotfit = /home/spicy/dotfiles.git"
]
prompt = "starship_prompt"

[line_editor]
edit_mode = "vi"
