# $PATH, set stuff in here to make it runnable from directory in the system
path = [
    # Texlab is a language server
    "/home/spicy/.opt/texlab-x86_64-linux",
    # Deno is a runtime for javascript
    "/home/spicy/.deno/bin",
    # Sass is a compiler for scss -> css
    "/home/spicy/.opt/dart-sass",
    # Npm is a node version manager
    "/home/spicy/.npm/bin",
    # Package manager for rust
    "/home/spicy/.cargo/bin",
    # Not sure if we need these 
    "/usr/local/sbin",
    "/usr/local/bin",
    "/usr/bin",
]

# Startup runs certain commands on startup
startup = [
    "alias dotgit = git --git-dir=$HOME/dotfiles.git/ --work-tree=$HOME",
    ""
]

# Starship is a cross-platform prompt for any shell
prompt = "starship prompt"

# Skip the welcome message
skip_welcome_message = true

# Set environment variables here
[env]
# Deno stuff
DENO_INSTALL = "/home/spicy/.deno"
# Editor settings
EDITOR = "nvim"
MANPAGER = "nvim +Man!"
PAGER = "nvim +Man!"
# FZF settings, include hidden files, allow ctrl + t
FZF_CTRL_T_COMMAND = "rg --files --hidden --ignore-case"
FZF_DEFAULT_COMMAND = "rg --files --hidden --ignore-case"
# Important looking stuff that I'm not sure if we need
# GTK_IM_MODULE= "fcitx"
# HOME = "/home/spicy"
# LANG = "en_US.UTF-8"
# LOGNAME = "spicy"
# MAIL = "/var/spool/mail/spicy"
# Make flags for c
# XAUTHORITY = "/home/spicy/.Xauthority"
# DISPLAY = ":0"
# SHELL = "/usr/bin/nu"
MAKEFLAGS = "-j$(nproc)"
# Fix for krita
QT_XCB_TABLET_LEGACY_COORDINATES = ""