include ${KITTY_OS}.conf

scrollback_lines 8000

# Window
window_padding_width 0
window_margin_width 0
window_border_width 0
# placement_strategy top-left
# placement_strategy center

# Perf
repaint_delay 0
input_delay 0
# turn to no if you don't care about battery or anythign
sync_to_monitor yes

# Font
font_family Maple Mono NF
font_size 13

# vim:ft=kitty

# include kanagawa.conf

# Debugging, uncomment when wanting to test
# cursor_blink_interval 0
# cursor_shape underline
# cursor #ffffff
# background #000000
# foreground #ffffff
# disable_ligatures always

# Keybindings, from @Elianiva
map alt+1 goto_tab 1
map alt+2 goto_tab 2
map alt+3 goto_tab 3
map alt+4 goto_tab 4
map alt+5 goto_tab 5
map alt+6 goto_tab 6
# map alt+n next_tab
# map alt+p previous_tab

# duplicate window
map kitty_mod+d new_tab_with_cwd 
map cmd+k 
# map alt+t kitten new_adjacent_tab.py
map alt+t launch --type=tab --location=after --cwd=current
map alt+w launch --location=after --cwd=current
map cmd+o combine : remote_control send_key  : remote_control send_text "\\n"

# Scrollback pager
# scrollback_pager nvim -u NONE -c "set nonumber nolist showtabline=0 foldcolumn=0 laststatus=0" -c "map <C-c> :qa!<CR>" -c "autocmd TermOpen * normal G" -c "silent write! /tmp/kitty_scrollback_buffer | te head -c-1 /tmp/kitty_scrollback_buffer; rm /tmp/kitty_scrollback_buffer; cat"
scrollback_pager nvim +Man!


# Macos specific

# for vim to actually read option key
# map opt_bs send_text all \x17
macos_quit_when_last_window_closed yes
confirm_os_window_close 0
allow_remote_control yes
listen_on unix:/tmp/kitty

# editor /opt/homebrew/bin/emacs
editor /usr/local/bin/nvim

enabled_layouts         grid,tall:bias=50;full_size=2, *
tab_bar_edge            top
tab_bar_style           slant
shell_integration enabled

paste_actions no-op

map ctrl+shift+backspace
map ctrl+shift+6      neighboring_window left
map ctrl+shift+7      neighboring_window down
map ctrl+shift+8      neighboring_window up
map ctrl+shift+9      neighboring_window right
enable_audio_bell no

