map ctrl+shift+backspace
map ctrl+shift+6      neighboring_window left
map ctrl+shift+7      neighboring_window down
map ctrl+shift+8      neighboring_window up
map ctrl+shift+9      neighboring_window right
enable_audio_bell no