# # script-opts=ytdl_hook-ytdl_path=/opt/homebrew/bin/yt-dlp
# 
# # video renderer
# vo=gpu-next
# 
# # crunchyroll style subtitles
# no-sub-ass # disable sub styling embedded into the subtitle file
# sub-border-size=5
# # sub-font-size=48
# # sub-margin-y=36
# sub-font='Trebuchet MS'
# sub-shadow-offset=2
# sub-shadow-color=0.0/0.0/0.0
# 
# # debug for subtitle styling
# # sid=1
# # start=00:00:55
# # fullscreen=yes
sub-pos=104
sub-scale=0.8
