set-option -sa terminal-overrides ",xterm*:Tc"
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

set -s extended-keys on
set -as terminal-features ',*ghostty*:extkeys'

run '~/.tmux/plugins/tpm/tpm'
