set-option -sa terminal-overrides ",xterm*:Tc"

set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

set -s extended-keys on
set -as terminal-features ',*ghostty*:extkeys'
set -g mouse on

# send-keys -M WheelUp
# send-keys -M WheelDown ??

unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

bind -T root F1 send-keys -t *:- "ts" "Enter"

# Use VI style keybgard shortcuts in copy mode
set-window-option -g mode-keys vi

# Use VI style keyboard shortcuts in the command prompt
set-option -g status-keys vi

set -g @resurrect-strategy-vim 'session'
set -g @resurrect-strategy-nvim 'session'
set -g @continuum-restore 'on'

source-file ~/.local/share/coffee/coffee.tmux

